# Generated by Django 3.2.5 on 2021-08-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
