# Generated by Django 3.2.5 on 2021-08-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_actor_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='Actors',
        ),
    ]
