# Generated by Django 3.2.5 on 2021-08-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('gmail', models.CharField(max_length=255)),
                ('client', models.BooleanField()),
                ('admin', models.BooleanField()),
                ('super_admin', models.BooleanField()),
            ],
        ),
    ]
