# Generated by Django 3.2.5 on 2021-08-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
